development:
  adapter: postgresql
  encoding: unicode
  database: beer_notes_with_ember_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: beer_notes_with_ember_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: beer_notes_with_ember_production
  pool: 5
